# Training a Graph Neural Network with NAGL with multiple objectives

This notebook will go through the process of training a new Graph Neural Network (GNN) on a small dataset of alkanes with multiple objectives. Please see the `train-gnn-notebook` tutorial for more on what's happening under the hood.


## Imports

In [1]:
from pathlib import Path

import numpy as np

from openff.toolkit import Molecule
from openff.units import unit

## Create the model

First, let's specify the model features.

In [2]:
from openff.nagl.features import atoms

atom_features = (
    atoms.AtomicElement(categories=["C", "H"]), # Is the atom Carbon or Hydrogen?
    atoms.AtomConnectivity(), # Is the atom bonded to 1, 2, 3, or 4 other atoms?
    atoms.AtomAverageFormalCharge(), # What is the atom's mean formal charge over the molecule's tautomers?
    atoms.AtomHybridization(), # What is the hybridization of the atom?
    atoms.AtomInRingOfSize(ring_size=3), # Is the atom in a 3-membered ring?
    atoms.AtomInRingOfSize(ring_size=4), # Is the atom in a 4-membered ring?
    atoms.AtomInRingOfSize(ring_size=5), # Is the atom in a 5-membered ring?
    atoms.AtomInRingOfSize(ring_size=6), # Is the atom in a 6-membered ring?
)

We also need to specify the architecture of the GNN. We can make this as complicated as we like.

In [3]:
from openff.nagl.config.model import (
    ConvolutionLayer,
    ConvolutionModule,
)
from openff.nagl import GNNModel
from openff.nagl.nn.gcn import SAGEConvStack
from torch.nn import ReLU
from openff.nagl.nn.postprocess import ComputePartialCharges

single_convolution_layer = ConvolutionLayer(
    hidden_feature_size=128,  # 128 features per hidden convolution layer
    aggregator_type="mean",  # aggregate atom representations with mean
    activation_function="ReLU", # max(0, x) activation function for layer
    dropout=0.0, # no dropout
)

convolution_module = ConvolutionModule(
    architecture="SAGEConv", # GraphSAGE GCN
    layers=[single_convolution_layer] * 3, # 3 hidden convolution layers        
)

We then specify the readout module.

In [4]:
from openff.nagl.config.model import (
    ForwardLayer,
    ReadoutModule,
)

single_readout_layer = ForwardLayer(
    hidden_feature_size=128,  # 128 features per hidden convolution layer
    activation_function="ReLU", # max(0, x) activation function for layer
    dropout=0.0, # no dropout
)

normal_readout_module = ReadoutModule(
    pooling="atoms",
    layers=[single_readout_layer] * 4, # 4 internal readout layers
    # calculate charges with charge equilibration scheme from
    # electronegativity and hardness
    postprocess="compute_partial_charges"
)
regularised_readout_module = ReadoutModule(
    pooling="atoms",
    layers=[single_readout_layer] * 4, # 4 internal readout layers
    # calculate charges with charge equilibration scheme from
    # electronegativity, hardness, and an initial charge prediction
    postprocess="regularized_compute_partial_charges"
)

Now we can put them together in a full `ModelConfig`. This can be passed to create a `GNNModel`. A model can have multiple readouts that derive different properties from the convolution representation, so each readout module is specified in a dictionary with a label.

Here, the [`GNNModel`] class represents all the hyperparameters for a model, but after we train it the same object will store weights as well.

[`GNNModel`]: https://docs.openforcefield.org/projects/nagl/en/latest/api/generated/openff.nagl.GNNModel.html

In [5]:
from openff.nagl.config.model import ModelConfig

model_config = ModelConfig(
    version="0.1",
    atom_features=atom_features,
    bond_features=[],
    convolution=convolution_module,
    readouts={
        "predicted-am1bcc-charges": normal_readout_module,
        "predicted-am1-charges": regularised_readout_module
    }
)

## Put together our datasets

We need to set up three datasets hers:

- **training**: Data the model is trained against

- **validation**: Data used to validate the model as it is trained

- **tests**: Data used to test that the final model is good

In this example, we'll use a collection of ten molecules for training. We'll also build a test/validation dataset of 3 molecules that are not in the training set.

We can use the [`LabelledDataset`] class to generate training data that is saved in the `training_data` directory (or use `pyarrow` directly). First we can generate the dataset from SMILES:

In [6]:
from openff.nagl.label.dataset import LabelledDataset

training_alkanes = [
    'C',
     'CC',
     'CCC',
     'CCCC',
     'CC(C)C',
     'CCCCC',
     'CC(C)CC',
     'CCCCCC',
     'CC(C)CCC',
     'CC(CC)CC',
]

training_dataset = LabelledDataset.from_smiles(
    "training_data",
    training_alkanes,
    mapped=False,
    overwrite_existing=True,
)
training_dataset.to_pandas()

                                       mapped_smiles
0                    [C:1]([H:2])([H:3])([H:4])[H:5]
1  [C:1]([C:2]([H:6])([H:7])[H:8])([H:3])([H:4])[...
2  [C:1]([C:2]([C:3]([H:9])([H:10])[H:11])([H:7])...
3  [C:1]([C:2]([C:3]([C:4]([H:12])([H:13])[H:14])...
4  [C:1]([C:2]([C:3]([H:9])([H:10])[H:11])([C:4](...
5  [C:1]([C:2]([C:3]([C:4]([C:5]([H:15])([H:16])[...
6  [C:1]([C:2]([C:3]([H:10])([H:11])[H:12])([C:4]...
7  [C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([H:18])([H...
8  [C:1]([C:2]([C:3]([H:11])([H:12])[H:13])([C:4]...
9  [C:1]([C:2]([C:3]([C:4]([H:13])([H:14])[H:15])...

Below we specify label functions to label our molecules with the information that we will use in training and testing. Each argument is specified and annotated to explain their purpose; however, all label functions can be instantiated with default arguments (e.g. `LabelConformers()`) unless you need specific column names or arguments (e.g. changing the charge method).

**Note: the ESP label function requires `openff-recharge` to be installed.**

In [7]:
from openff.nagl.label.labels import (
    LabelConformers,
    LabelCharges,
    LabelMultipleDipoles,
    LabelMultipleESPs,
)
import openff.recharge

# generate ELF conformers
label_conformers = LabelConformers(
    # create a new 'conformers' with output conformers
    conformer_column="conformers",
    # create a new 'n_conformers' with number of conformers
    n_conformer_column="n_conformers",
    n_conformer_pool=500, # initially generate 500 conformers
    n_conformers=10, # prune to max 10 conformers
    rms_cutoff=0.05,
)

# generate AM1 charges
label_am1_charges = LabelCharges(
    charge_method="am1-mulliken", # AM1
    # use previously generate conformers instead of new ones
    use_existing_conformers=True,
    # use the 'conformers' column as input for charge assignment
    conformer_column="conformers",
    # write generated charges to 'target-am1-charges' column
    charge_column="target-am1-charges",
)

# generate AM1-BCC charges
label_am1bcc_charges = LabelCharges(
    charge_method="am1bcc", # AM1BCC
    # use previously generate conformers instead of new ones
    use_existing_conformers=True,
    # use the 'conformers' column as input for charge assignment
    conformer_column="conformers",
    # write generated charges to 'target-am1bcc-charges' column
    charge_column="target-am1bcc-charges",
)

label_am1bcc_dipoles = LabelMultipleDipoles(
    # use the 'conformers' column as input to calculate dipole moments
    conformer_column="conformers",
    # use the 'n_conformers' column as input
    n_conformer_column="n_conformers",
    # use the "target-am1bcc-charges" column as input to calculate dipole moments
    charge_column="target-am1bcc-charges",
    # write calculated dipoles to 'target-am1bcc-dipoles' column
    dipole_column="target-am1bcc-dipoles",
)

label_am1bcc_esps = LabelMultipleESPs(
    # use the 'conformers' column as input to calculate ESPs
    conformer_column="conformers",
    # use the 'n_conformers' column as input
    n_conformer_column="n_conformers",
    # use the "target-am1bcc-charges" column as input to calculate ESPS
    charge_column="target-am1bcc-charges",
    # generate new grids and inverse distances to points
    use_existing_inverse_distances=False,
    # write inverse distances from conformer to surface to this column
    inverse_distance_matrix_column="grid_inverse_distances",
    # write number of grid points for each surface to this column
    grid_length_column="esp_lengths",
    # write calculated ESPs to 'esps' column
    esp_column="esps",
)

Below we apply the label functions to actually generate the labels. The order matters, as later label functions use the output of earlier ones.

In [8]:
labellers = [
    label_conformers, # generate initial conformers,
    label_am1_charges,
    label_am1bcc_charges,
    label_am1bcc_dipoles,
    label_am1bcc_esps,
]

training_dataset.apply_labellers(labellers)
training_dataset.to_pandas()

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)
/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)
/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

,mapped_smiles,conformers,n_conformers,target-am1-charges,target-am1bcc-charges,target-am1bcc-dipoles,esp_lengths,grid_inverse_distances,esps
0,[C:1]([H:2])([H:3])([H:4])[H:5],"[0.005118712612069831, -0.010620498663889949, ...",1,"[-0.2656, 0.0664, 0.0664, 0.0664, 0.0664]","[-0.1084, 0.0271, 0.0271, 0.0271, 0.0271]","[-0.0006935855589354639, 0.001439077568957078,...",[398],"[0.22234336592604093, 0.16919800884004924, 0.2...","[-0.0004840379389589068, -0.000719721399576947..."
1,[C:1]([C:2]([H:6])([H:7])[H:8])([H:3])([H:4])[...,"[-0.7476366827021611, 0.04183756987532164, 0.0...",1,"[-0.21225, -0.21225, 0.07075, 0.07075, 0.07075...","[-0.09435, -0.09435, 0.03145, 0.03145, 0.03145...","[-0.00041758620441836175, -0.00538507227854946...",[496],"[0.22234336592604093, 0.18757653103125116, 0.3...","[-0.0013845549815025768, -0.002919251364357059..."
2,[C:1]([C:2]([C:3]([H:9])([H:10])[H:11])([H:7])...,"[1.217152984776736, -0.2427629117673087, 0.210...",1,"[-0.211, -0.16, -0.211, 0.072, 0.072, 0.071, 0...","[-0.09310018181818182, -0.08140018181818182, -...","[-0.004730849295705435, -0.0099036645566341, 0...",[602],"[0.22234336592604093, 0.20444340100593922, 0.1...","[-0.002897594388970577, -0.00096461633096685, ..."
3,[C:1]([C:2]([C:3]([C:4]([H:12])([H:13])[H:14])...,"[1.891468422129933, 0.051344513264112185, 0.24...",1,"[-0.21028571428571427, -0.15928571428571428, -...","[-0.09238585714285714, -0.08068585714285714, -...","[-0.003913810727719819, -0.0051085581947480085...",[695],"[0.22234336592604093, 0.17093193901394518, 0.1...","[-0.0009134260983215681, 2.1779035910935232e-0..."
4,[C:1]([C:2]([C:3]([H:9])([H:10])[H:11])([C:4](...,"[1.4395471764526913, 0.2764834314806461, 0.136...",1,"[-0.20735714285714285, -0.10935714285714285, -...","[-0.08945692857142856, -0.07005692857142856, -...","[-0.005837276089204181, -0.00952804644804893, ...",[676],"[0.22234336592604093, 0.19078340505614977, 0.1...","[-0.000862320615205938, -0.0033680575577770995..."
5,[C:1]([C:2]([C:3]([C:4]([C:5]([H:15])([H:16])[...,"[2.4653833360039563, -0.04588079514691061, 0.0...",1,"[-0.21, -0.159, -0.158, -0.159, -0.21, 0.07200...","[-0.09210011764705882, -0.08040011764705882, -...","[-0.004338372099247187, 0.00563319678122937, 0...",[787],"[0.22234336592604093, 0.1419069000440735, 0.12...","[0.00046487740775592694, 0.0001720329154335353..."
6,[C:1]([C:2]([C:3]([H:10])([H:11])[H:12])([C:4]...,"[-1.2553449739454556, 1.0455464122726073, 0.03...",1,"[-0.207, -0.10599999999999998, -0.207, -0.153,...","[-0.08909988235294117, -0.06669988235294116, -...","[-0.0008746985584004857, -0.009802552244059657...",[764],"[0.22234336592604093, 0.15256634736217198, 0.1...","[-0.0004691810804953204, -0.001426478296616263..."
7,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([H:18])([H...,"[-3.0866505208004993, -0.19318766577556695, -0...",1,"[-0.21009999999999998, -0.1591, -0.1581, -0.15...","[-0.0922, -0.0805, -0.0795, -0.0795, -0.0805, ...","[0.0022991477813734673, -0.016943484604316585,...",[908],"[0.22234336592604093, 0.19916205655575062, 0.1...","[-0.0012872440678623996, -9.717755939488495e-0..."
8,[C:1]([C:2]([C:3]([H:11])([H:12])[H:13])([C:4]...,"[-1.349605809430762, 1.2814441466436928, -0.33...",1,"[-0.20694999999999997, -0.10694999999999998, -...","[-0.08955004999999999, -0.06765004999999999, -...","[-0.011423378526822306, 0.003635155692599444, ...",[844],"[0.22234336592604093, 0.18702403117186636, 0.1...","[-0.001386396446852449, -0.002495649132384172,..."
9,[C:1]([C:2]([C:3]([C:4]([H:13])([H:14])[H:15])...,"[-0.3994646663766072, -1.422662911831976, -0.9...",1,"[-0.20794999999999997, -0.10594999999999999, -...","[-0.09005, -0.06665, -0.07785, -0.09205, -0.07...","[0.00010295224717736529, -0.012780436276269232...",[826],"[0.22234336592604093, 0.143556451848822, 0.118...","[-0.0004796824938001244, -0.000251064571382349..."

### Building a test dataset

To augment the provided training set, we'll quickly prepare a second dataset for testing and validation. We use the same label functions:

In [9]:
from openff.nagl.label.labels import LabelCharges

# Choose the molecules to put in this dataset
# Note that these molecules aren't in the training dataset!
test_smiles = [
    "CCCCCCC",
    "CC(C)C(C)C",
    "CC(C)(C)C",
]

test_dataset = LabelledDataset.from_smiles(
    "my_first_test_dataset",  # path to save to
    test_smiles,
    mapped=False,
    overwrite_existing=True,
)

test_dataset.apply_labellers(labellers)
test_dataset.to_pandas()

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/openff/toolkit/utils/toolkit_registry.py:262: UserWarning: `NAGLToolkitWrapper.assign_partial_charges` was passed optional argument `use_conformers` which will not be used. OpenFF NAGL does not generate conformers as part of assigning partial charges.
  return method(*args, **kwargs)

,mapped_smiles,conformers,n_conformers,target-am1-charges,target-am1bcc-charges,target-am1bcc-dipoles,esp_lengths,grid_inverse_distances,esps
0,[C:1]([C:2]([C:3]([C:4]([C:5]([C:6]([C:7]([H:2...,"[-3.546068940192181, 0.5935908094613401, 0.079...",2,"[-0.21002173913043476, -0.15852173913043477, -...","[-0.09212165217391305, -0.07967165217391305, -...","[-0.009615358253986128, -0.0002798842053785, 0...","[938, 920]","[0.22234336592604093, 0.2210411406187215, 0.14...","[-0.001142825009267422, -0.0004387578689014348..."
1,[C:1]([C:2]([C:3]([H:11])([H:12])[H:13])([C:4]...,"[0.9780009691126561, -0.9290358087611312, 0.93...",1,"[-0.20589999999999997, -0.10289999999999998, -...","[-0.0890002, -0.06360020000000001, -0.0890002,...","[-0.0018496136981201866, -0.010091856232488358...",[800],"[0.22234336592604093, 0.17975898869235699, 0.1...","[-0.0010385182129426934, -0.000104253227320133..."
2,[C:1]([C:2]([C:3]([H:9])([H:10])[H:11])([C:4](...,"[1.2931714944742823, -0.7654495089444694, -0.0...",1,"[-0.20323529411764704, -0.06023529411764704, -...","[-0.08533529411764705, -0.06023529411764706, -...","[0.0033685192825578057, 0.010316515532278664, ...",[743],"[0.22234336592604093, 0.16293914207377258, 0.1...","[6.830848951213352e-06, 0.00040370881189352205..."

### Curating our data module

Now we assemble our datasets into a `DataConfig`. For each `DatasetConfig`, we need to specify the targets we are choosing to fit. A `Target` is what we used to construct the objective function and calculate loss. Below we:
- fit the `predicted-am1-charges` property directly to the labelled `target-am1-charges`
- fit the `predicted-am1bcc-charges` property to a combined objective of:
  - charge RMSE
  - dipole moments
  - ESP targets
 
For the physical properties, we need additional information (the `conformers`, `n_conformers`, ... columns) to calculate the dipole moments and ESPs for comparison. Each of these has been annotated. The `target_label` always refers to the column in the input dataset that is the property we are comparing.

In [10]:
from openff.nagl.config.data import DatasetConfig, DataConfig
from openff.nagl.training.metrics import RMSEMetric
from openff.nagl.training.loss import ReadoutTarget, MultipleDipoleTarget, MultipleESPTarget


am1_charge_rmse_target = ReadoutTarget(
    metric=RMSEMetric(),  # use RMSE to calculate loss
    target_label="target-am1-charges", # column to use from data as reference target
    prediction_label="predicted-am1-charges", # readout value to compare to target
    denominator=1.0, # denominator to normalise loss -- important for multi-target objectives
    weight=1.0, # how much to weight the loss -- important for multi-target objectives
)

am1bcc_charge_rmse_target = ReadoutTarget(
    metric=RMSEMetric(),  # use RMSE to calculate loss
    target_label="target-am1bcc-charges", # column to use from data as reference target
    prediction_label="predicted-am1bcc-charges", # readout value to compare to target
    denominator=0.001, # denominator to normalise loss -- important for multi-target objectives
    weight=1.0, # how much to weight the loss -- important for multi-target objectives
)

am1bcc_dipole_target = MultipleDipoleTarget(
    metric=RMSEMetric(),
    target_label="target-am1bcc-dipoles", # column to use from input data as reference target
    charge_label="predicted-am1bcc-charges", # readout charge value to calculate dipoles with
    conformation_column="conformers", # input data to use for calculating dipoles
    n_conformation_column="n_conformers", # input data to use for calculating dipoles
    denominator=0.01,
    weight=1.0
)

am1bcc_esp_target = MultipleESPTarget(
    metric=RMSEMetric(),
    target_label="esps", # column to use from input data as reference target
    charge_label="predicted-am1bcc-charges", # readout charge value to calculate ESPs with
    inverse_distance_matrix_column="grid_inverse_distances", # input data to use to calculate ESPs
    esp_length_column="esp_lengths", # input data to use to calculate ESPs
    n_esp_column="n_conformers", # input data to use to calculate ESPs
    denominator=0.001,
    weight=1.0
)

Now we combine each of these targets into each `DatasetConfig`.

In [11]:
targets = [
    am1_charge_rmse_target,
    am1bcc_charge_rmse_target,
    am1bcc_dipole_target,
    am1bcc_esp_target,
]
    

training_dataset_config = DatasetConfig(
    sources=["training_data"],
    targets=targets,
    batch_size=1000,
)

test_dataset_config = validation_dataset_config = DatasetConfig(
    sources=["my_first_test_dataset"],
    targets=targets,
    batch_size=1000,
)

data_config = DataConfig(
    training=training_dataset_config,
    validation=validation_dataset_config,
    test=test_dataset_config
)

## Train the model

We've prepared our model architecture and our training, validation and test data; now we just need to fit the model! To do this, we need to specify optimization settings with a `OptimizerConfig`, and then put everything together in a `TrainingConfig`.

In [12]:
from openff.nagl.config.optimizer import OptimizerConfig
from openff.nagl.config.training import TrainingConfig

optimizer_config = OptimizerConfig(
    optimizer="Adam",
    learning_rate=0.001,
)

training_config = TrainingConfig(
    model=model_config,
    data=data_config,
    optimizer=optimizer_config
)

In [13]:
from openff.nagl.training.training import TrainingGNNModel, DGLMoleculeDataModule

training_model = TrainingGNNModel(training_config)
data_module = DGLMoleculeDataModule(training_config)

To properly fit the model, we use the [`Trainer`] class from PyTorch Lightning. This allows us to configure how data and progress are stored and reported using callbacks. The [`fit()`] method trains and validates against the data module we provide it: 

[`Trainer`]: https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
[`fit()`]: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer.fit

In [14]:
from pytorch_lightning import Trainer

trainer = Trainer(max_epochs=200)

trainer.progress_bar_callback.disable()
trainer.checkpoint_callback.monitor = "val/loss"

trainer.fit(
    training_model,
    datamodule=data_module
)

GPU available: False, used: False

TPU available: False, using: 0 TPU cores

💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/10 [00:00<?, ?it/s]

Featurizing batch:  90%|█████████ | 9/10 [00:00<00:00, 82.49it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 74.40it/s]

Featurizing dataset: 1it [00:00,  5.04it/s]

Featurizing dataset: 1it [00:00,  5.02it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 32.87it/s]

Featurizing dataset: 1it [00:00,  6.58it/s]

Featurizing dataset: 1it [00:00,  6.45it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 49.21it/s]

Featurizing dataset: 1it [00:00,  8.08it/s]

Featurizing dataset: 1it [00:00,  8.04it/s]

2026-08-07 02:17:20.651675: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/10 [00:00<?, ?it/s]

Featurizing batch:  80%|████████  | 8/10 [00:00<00:00, 79.07it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 61.05it/s]

Featurizing dataset: 1it [00:00,  4.48it/s]

Featurizing dataset: 1it [00:00,  4.47it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 61.38it/s]

Featurizing dataset: 1it [00:00,  9.00it/s]

Featurizing dataset: 1it [00:00,  8.95it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 59.36it/s]

Featurizing dataset: 1it [00:00, 11.51it/s]

┏━━━┳━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name  ┃ Type     ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model │ GNNModel │  203 K │ train │     0 │
└───┴───────┴──────────┴────────┴───────┴───────┘

Trainable params: 203 K
Non-trainable params: 0
Total params: 203 K
Total estimated model params size (MB): 0.812
Modules in train mode: 57
Modules in eval mode: 0
Total FLOPs: 0

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.
/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py:321: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

`Trainer.fit` stopped: `max_epochs=200` reached.

## Results!

We can use the `Trainer` object's [`test()`] method to evaluate the model against our test data:

[`test()`]: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html#pytorch_lightning.trainer.trainer.Trainer.test

In [15]:
trainer.test(training_model, data_module)

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/10 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 91.11it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 89.49it/s]

Featurizing dataset: 1it [00:00,  5.55it/s]

Featurizing dataset: 1it [00:00,  5.53it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 67.47it/s]

Featurizing dataset: 1it [00:00, 11.76it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 59.54it/s]

Featurizing dataset: 1it [00:00, 11.28it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/10 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 89.13it/s]

Featurizing batch: 100%|██████████| 10/10 [00:00<00:00, 87.55it/s]

Featurizing dataset: 1it [00:00,  5.52it/s]

Featurizing dataset: 1it [00:00,  5.49it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 48.46it/s]

Featurizing dataset: 1it [00:00,  7.45it/s]

Featurizing dataset: 1it [00:00,  7.37it/s]

Featurizing dataset: 0it [00:00, ?it/s]

Featurizing batch:   0%|          | 0/3 [00:00<?, ?it/s]

Featurizing batch: 100%|██████████| 3/3 [00:00<00:00, 56.01it/s]

Featurizing dataset: 1it [00:00, 10.10it/s]

/home/runner/micromamba/envs/openff-docs-examples/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:434: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=3` in the `DataLoader` to improve performance.

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                      Test metric                       ┃                      DataLoader 0                      ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│         test/esps/multiple_esps/rmse/1.0/0.001         │                   0.0649193599820137                   │
│                       test/loss                        │                   3.3635549545288086                   │
│      test/target-am1-charges/readout/rmse/1.0/1.0      │                   0.0136081762611866                   │
│   test/target-am1bcc-charges/readout/rmse/1.0/0.001    │                   3.164639472961426                    │
│ test/target-am1bcc-dipoles/multiple_dipoles/rmse/1.0/… │                  0.12038778513669968                   │
└────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────┘

[{'test/target-am1-charges/readout/rmse/1.0/1.0': 0.0136081762611866,
  'test/target-am1bcc-charges/readout/rmse/1.0/0.001': 3.164639472961426,
  'test/target-am1bcc-dipoles/multiple_dipoles/rmse/1.0/0.01': 0.12038778513669968,
  'test/esps/multiple_esps/rmse/1.0/0.001': 0.0649193599820137,
  'test/loss': 3.3635549545288086}]

We can isolate the model itself from all the training requirements:

In [16]:
model = training_model.model

Octane isn't in any of our data, so the model hasn't seen it yet! We can predict its partial charges with the [`compute_property()`] method:

[`compute_property()`]: https://docs.openforcefield.org/projects/nagl/en/stable/api/generated/openff.nagl.GNNModel.html#openff.nagl.GNNModel.compute_property

In [17]:
octane = Molecule.from_smiles("CCCCCCCC")

am1bcc_charges = model.compute_property(octane, readout_name="predicted-am1bcc-charges")

And we can compare that to the AM1BCC partial charges produced by the OpenFF Toolkit:

In [18]:
octane.assign_partial_charges("am1bcc")
octane.partial_charges

<Quantity([-0.093023 -0.080323 -0.078323 -0.078323 -0.078323 -0.078323 -0.080323
 -0.093023  0.03211   0.03211   0.03211   0.038777  0.038777  0.038777
  0.038777  0.039277  0.039277  0.039277  0.039277  0.038777  0.038777
  0.038777  0.038777  0.03211   0.03211   0.03211 ], 'elementary_charge')>

In [19]:
prediction = am1bcc_charges * unit.elementary_charge
np.abs(prediction - octane.partial_charges)

<Quantity([0.00443832 0.00310125 0.00247964 0.00289596 0.00289596 0.00247964
 0.00310125 0.00443832 0.00084499 0.00084499 0.00084499 0.00214001
 0.00214001 0.00127498 0.00127498 0.00177498 0.00177498 0.00177498
 0.00177498 0.00127498 0.00127498 0.00214001 0.00214001 0.00084499
 0.00084499 0.00084499], 'elementary_charge')>

All within 0.002 elementary charge units of true AM1BCC charges! Not too bad!

Similarly, looking at AM1 charges:

In [20]:
am1_charges = model.compute_property(octane, readout_name="predicted-am1-charges")
am1_charges

array([-0.233656  , -0.17453541, -0.17400591, -0.17252222, -0.17252222,
       -0.17400591, -0.17453541, -0.233656  ,  0.07904727,  0.07904727,
        0.07904727,  0.08535674,  0.08535674,  0.08671597,  0.08671597,
        0.08671597,  0.08671597,  0.08671597,  0.08671597,  0.08671597,
        0.08671597,  0.08535674,  0.08535674,  0.07904727,  0.07904727,
        0.07904727], dtype=float32)

In [21]:
octane.assign_partial_charges("am1-mulliken")
octane.partial_charges

<Quantity([-0.21096154 -0.15896154 -0.15696154 -0.15696154 -0.15696154 -0.15696154
 -0.15896154 -0.21096154  0.07103846  0.07103846  0.07203846  0.07903846
  0.07803846  0.07903846  0.07703846  0.07903846  0.07803846  0.07903846
  0.07803846  0.07903846  0.07703846  0.07803846  0.07803846  0.07103846
  0.07103846  0.07203846], 'elementary_charge')>

In [22]:
am1_prediction = am1_charges * unit.elementary_charge
np.abs(am1_prediction - octane.partial_charges)

<Quantity([0.02269447 0.01557387 0.01704437 0.01556068 0.01556068 0.01704437
 0.01557387 0.02269447 0.00800881 0.00800881 0.00700881 0.00631828
 0.00731828 0.0076775  0.0096775  0.0076775  0.0086775  0.0076775
 0.0086775  0.0076775  0.0096775  0.00731828 0.00731828 0.00800881
 0.00800881 0.00700881], 'elementary_charge')>

This is slightly less accurate (to within 0.02 elementary charge), possibly because AM1 charges were only fit to the charges directly, with none of the physical properties.

## Saving and loading our model

We can save the final model with the `model.save()` method. This'll let us store it for later.

In [23]:
model.save("trained_alkane_model.pt")

When we want it again, we can use the `GNNModel.load()` method:

In [24]:
model_from_disk = GNNModel.load("trained_alkane_model.pt")
model_from_disk.compute_property(octane, readout_name="predicted-am1bcc-charges")

array([-0.08858468, -0.07722175, -0.07584336, -0.07542704, -0.07542704,
       -0.07584336, -0.07722175, -0.08858468,  0.03126501,  0.03126501,
        0.03126501,  0.03663699,  0.03663699,  0.03750202,  0.03750202,
        0.03750202,  0.03750202,  0.03750202,  0.03750202,  0.03750202,
        0.03750202,  0.03663699,  0.03663699,  0.03126501,  0.03126501,
        0.03126501], dtype=float32)